### ISSUE TITLE
Homework 1, question 2: It is not recommended to hard-code values

### ISSUE THREAD

**Issue by bokov** [frkndrsn/TSCI5050#2]
https://github.com/frkndrsn/TSCI5050/blob/efa72750104b009f52aaed22736f42de59e3cdfd/dat1.R#L3-L8

The purpose of this exercise is to write code that will work on any dataset. Here are some hints...

1. In addition to numbers you can use a vector of `TRUE` and `FALSE` in the first (rows) argument when subsetting the data.frame. Rows having `TRUE` will be kept and those having `FALSE` will be omitted. You do not need a value for each row, though-- that is inefficient and may lead to errors if the number of rows in your data changes. Instead, you can use a shorter vector and when it runs out of values it will repeat. For example, if you wanted to keep every _third_ row, you could use `dat0[c(FALSE,FALSE,TRUE),]`. That will expand to `c(FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,... etc.)` You can adapt this to help you correct your answers to questions 2 and 3 of this homework.
2. You do not need to write a separate command for each numeric column. Install the `tidyverse` package (in your console, not in the script), add `library(tidyverse)` at the top of your script, and then use the `select_if` function it provides in the second (columns) argument when subsetting the data.frame (for example, `select(dat0, is.numeric)`)
3. Please note that the homework asks you to put a comment above each section of code indicating which question it answers. Additional comments are encouraged.

**Comment by frkndrsn** [comment]
it is much easier than the way I did :)
